version: "3.4"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  emailservice:
    image: andris9/emailengine
    depends_on:
      - redis
    environment:
      - EENGINE_REDIS=redis://host.docker.internal:6379/7
    ports:
      - 80:3000
